using System;
using System.Collections.Generic;

namespace UnityEngine.XR.iOS
{
	public class CarARHitTest : MonoBehaviour
	{
		public Transform m_HitTransform;
		public float maxRayDistance = 30.0f;
		public LayerMask collisionLayer = 1 << 10;  //ARKitPlane layer

		public GameObject CarPrefab;

		//public GameObject PlanePrefab;

        public static GameObject CarHolder;
		//public static GameObject PlaneHolder;

		void CarCreate(Vector3 position){
			CarHolder = GameObject.Instantiate (CarPrefab, position, Quaternion.identity);
		}
		
		bool HitTestWithResultType (ARPoint point, ARHitTestResultType resultTypes)
        {
            List<ARHitTestResult> hitResults = UnityARSessionNativeInterface.GetARSessionNativeInterface ().HitTest (point, resultTypes);
            if (hitResults.Count > 0) {
                foreach (var hitResult in hitResults) {
                    Debug.Log ("Got hit!");
                    //m_HitTransform.position = UnityARMatrixOps.GetPosition (hitResult.worldTransform);
                    //m_HitTransform.rotation = UnityARMatrixOps.GetRotation (hitResult.worldTransform);
					
					CarHolder.transform.position = UnityARMatrixOps.GetPosition (hitResult.worldTransform);
					CarHolder.transform.rotation = UnityARMatrixOps.GetRotation (hitResult.worldTransform);
					//PlaneHolder.transform.position = UnityARMatrixOps.GetPosition (hitResult.worldTransform);
					
					//PlaneHolder.transform.rotation = UnityARMatrixOps.GetRotation (hitResult.worldTransform);


					// CarCreate(new Vector3(
					// 		UnityARMatrixOps.GetPosition(hitResult.worldTransform).x,
					// 		UnityARMatrixOps.GetPosition(hitResult.worldTransform).y,
					// 		UnityARMatrixOps.GetPosition(hitResult.worldTransform).z));
					
                    Debug.Log (string.Format ("x:{0:0.######} y:{1:0.######} z:{2:0.######}", m_HitTransform.position.x, m_HitTransform.position.y, m_HitTransform.position.z));
                    return true;
                }
            }
            return false;
        }

		void Start () {
			// CarCreate(new Vector3(
			// 				0,
			// 				0.6f,
			// 				1));
			CarHolder = GameObject.Instantiate(CarPrefab,new Vector3(0,0.6f,1),Quaternion.identity);
			//PlaneHolder = GameObject.Instantiate(PlanePrefab,new Vector3(0,0.6f,1),Quaternion.identity);
			CarHolder.transform.localScale = new Vector3(0.05f,0.05f,0.05f);
			//PlaneHolder.transform.localScale = new Vector3(0.01f,0.01f,0.01f);
			Debug.Log("Create Car!!!!!!!!!!!!!!!!!!!!!!!");
		}
		
		// Update is called once per frame
		void Update () {
			#if UNITY_EDITOR   //we will only use this script on the editor side, though there is nothing that would prevent it from working on device
			if (Input.GetMouseButtonDown (0)) {
				Ray ray = Camera.main.ScreenPointToRay (Input.mousePosition);
				RaycastHit hit;
				

				//we'll try to hit one of the plane collider gameobjects that were generated by the plugin
				//effectively similar to calling HitTest with ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent
				if (Physics.Raycast (ray, out hit, maxRayDistance, collisionLayer)) {
					//we're going to get the position from the contact point
					m_HitTransform.position = hit.point;
					Debug.Log (string.Format ("x:{0:0.######} y:{1:0.######} z:{2:0.######}", m_HitTransform.position.x, m_HitTransform.position.y, m_HitTransform.position.z));

					//and the rotation from the transform of the plane collider
					m_HitTransform.rotation = hit.transform.rotation;
				}
			}
			#else
			if (Input.touchCount > 0 && m_HitTransform != null)
			{
				var touch = Input.GetTouch(0);
				if (touch.phase == TouchPhase.Began || touch.phase == TouchPhase.Moved)
				{
					var screenPosition = Camera.main.ScreenToViewportPoint(touch.position);
					ARPoint point = new ARPoint {
						x = screenPosition.x,
						y = screenPosition.y
					};

                    // prioritize reults types
                    ARHitTestResultType[] resultTypes = {
						//ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingGeometry,
                        ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent, 
                        // if you want to use infinite planes use this:
                        //ARHitTestResultType.ARHitTestResultTypeExistingPlane,
                        //ARHitTestResultType.ARHitTestResultTypeEstimatedHorizontalPlane, 
						//ARHitTestResultType.ARHitTestResultTypeEstimatedVerticalPlane, 
						//ARHitTestResultType.ARHitTestResultTypeFeaturePoint
                    }; 
					
                    foreach (ARHitTestResultType resultType in resultTypes)
                    {
                        if (HitTestWithResultType (point, resultType))
                        {
                            return;
                        }
                    }
				}
			}
			#endif

		}

	
	}
}

